:jbake-title: Bausteinsicht
:jbake-type: page_toc
:jbake-status: published
:jbake-menu: arc42
:jbake-order: 5
:filename: /modules/ROOT/pages/05_building_block_view.adoc
:plantuml-server-url: http://www.plantuml.com/plantuml
ifndef::imagesdir[:imagesdir: ../assets/images]

ifndef::optimize-content[]
:toc:
endif::optimize-content[]

[[section-building-block-view]]
// == Bausteinsicht
ifdef::showArc42Help[]
****
https://c4model.com/[C4 Model]
****
endif::[]

== Container

ifdef::showArc42Help[]
****
Once you understand how your system fits in to the overall IT environment, a really useful next step is to zoom-in to the system boundary with a Container diagram. A "container" is something like a server-side web application, single-page application, desktop application, mobile app, database schema, file system, etc. Essentially, a container is a separately runnable/deployable unit (e.g. a separate process space) that executes code or stores data.

The Container diagram shows the high-level shape of the software architecture and how responsibilities are distributed across it. It also shows the major technology choices and how the containers communicate with one another. It's a simple, high-level technology focussed diagram that is useful for software developers and support/operations staff alike.
****
endif::[]

[plantuml, svg]
----
include::example$container-diagram.puml[]
----

== Components

ifdef::showArc42Help[]
****
Next you can zoom in and decompose each container further to identify the major structural building blocks and their interactions.

The Component diagram shows how a container is made up of a number of "components", what each of those components are, their responsibilities and the technology/implementation details.
****
endif::[]

[plantuml, svg]
----
include::example$component-diagram.puml[]
----

=== Code

ifdef::showArc42Help[]
****
Finally, you can zoom in to each component to show how it is implemented as code; using UML class diagrams, entity relationship diagrams or similar.

This is an optional level of detail and is often available on-demand from tooling such as IDEs. Ideally this diagram would be automatically generated using tooling (e.g. an IDE or UML modelling tool), and you should consider showing only those attributes and methods that allow you to tell the story that you want to tell. This level of detail is not recommended for anything but the most important or complex components.
****
endif::[]

