:jbake-title: Laufzeitsicht
:jbake-type: page_toc
:jbake-status: published
:jbake-menu: arc42
:jbake-order: 6
:filename: /modules/ROOT/pages/06_runtime_view.adoc
:plantuml-server-url: http://www.plantuml.com/plantuml
ifndef::imagesdir[:imagesdir: ../assets/images]

ifndef::optimize-content[]
:toc:
endif::optimize-content[]


[[section-runtime-view]]
== Laufzeitsicht

ifdef::showArc42Help[]
****
.Inhalt
Diese Sicht erklärt konkrete Abläufe und Beziehungen zwischen Bausteinen in Form von Szenarien aus den folgenden Bereichen:

*  Wichtige Abläufe oder _Features_:
Wie führen die Bausteine der Architektur die wichtigsten Abläufe durch?
*  Interaktionen an kritischen externen Schnittstellen:
Wie arbeiten Bausteine mit Nutzern und Nachbarsystemen zusammen?
* Betrieb und Administration: Inbetriebnahme, Start, Stop.
* Fehler- und Ausnahmeszenarien

Anmerkung:
Das Kriterium für die Auswahl der möglichen Szenarien (d.h. Abläufe) des Systems ist deren Architekturrelevanz.
Es geht nicht darum, möglichst viele Abläufe darzustellen, sondern eine angemessene Auswahl zu dokumentieren.

.Motivation
Sie sollten verstehen, wie (Instanzen von) Bausteine(n) Ihres Systems ihre jeweiligen Aufgaben erfüllen und zur Laufzeit miteinander kommunizieren.

Nutzen Sie diese Szenarien in der Dokumentation hauptsächlich für eine verständlichere Kommunikation mit denjenigen Stakeholdern, die die statischen Modelle (z.B. Bausteinsicht, Verteilungssicht) weniger verständlich finden.

.Form
Für die Beschreibung von Szenarien gibt es zahlreiche Ausdrucksmöglichkeiten.
Nutzen Sie beispielsweise:

* Nummerierte Schrittfolgen oder Aufzählungen in Umgangssprache
* Aktivitäts- oder Flussdiagramme
* Sequenzdiagramme
* BPMN (Geschäftsprozessmodell und -notation) oder EPKs (Ereignis-Prozessketten)
* Zustandsautomaten
* ...

.Weiterführende Informationen

Siehe https://docs.arc42.org/section-6/[Laufzeitsicht] in der online-Dokumentation (auf Englisch!).

****
endif::[]

=== _Authorisierung REST API_

Entgegen anfänglicher Annahmen, wurde von der SVS ein Sicherheitssystem gewünscht. Alle vom Webbrowser erreichbaren Endpunkte wurden mit Basic Auth gesichert. Die API wird mit JWTs geschützt.

[%autowidth.stretch]
|===
|Endpoint |Sicherheit |Erläuterung

| _/api/v1/auth_
| _Basic Auth_
| _POST - generiert Token_

| _/api/v1/trl_
| _Bearer Token_
| _POST - empfängt Daten die vom TRL berechnet werden sollen_

| _/api/v1/version_
| _Bearer Token_
| _GET - Versionsabfrage Rechenkern_

| _/api/swagger /actuator ...usw._
| _Basic Auth_
| _Endpunkte für Webbrowser_
|===
