:jbake-title: Glossar
:jbake-type: page_toc
:jbake-status: published
:jbake-menu: arc42
:jbake-order: 12
:filename: /modules/ROOT/pages/12_glossary.adoc
:plantuml-server-url: http://www.plantuml.com/plantuml
ifndef::imagesdir[:imagesdir: ../assets/images]

ifndef::optimize-content[]
:toc:
endif::optimize-content[]


[[section-glossary]]
== Glossar

ifdef::showArc42Help[]
****
.Inhalt
Die wesentlichen fachlichen und technischen Begriffe, die Stakeholder im Zusammenhang mit dem System verwenden.

Nutzen Sie das Glossar ebenfalls als Übersetzungsreferenz, falls Sie in mehrsprachigen Teams arbeiten.

.Motivation
Sie sollten relevante Begriffe klar definieren, so dass alle Beteiligten

* diese Begriffe identisch verstehen, und
* vermeiden, mehrere Begriffe für die gleiche Sache zu haben.

.Form

Zweispaltige Tabelle mit <Begriff> und <Definition>.

Eventuell weitere Spalten mit Übersetzungen, falls notwendig.


.Weiterführende Informationen

Siehe https://docs.arc42.org/section-12/[Glossar] in der online-Dokumentation (auf Englisch!).

****
endif::[]

[cols="e,2e" options="header"]
|===
|Begriff |Definition

|...
|...

|===
